<?xml version="1.0" encoding="UTF-8"?>
<project basedir="." name="mholmes.com" default="all">
  <description>
      This build file handles the creation of the website.
      
      Just type:
      
      ant
      
      at the command line to run the full build. The results will appear in 
      the /products/ folder.
      
  </description>
  
    <property name="echo.separator" value="************************************************"/>
    
    <!-- We'll need access to the date. -->
    <tstamp>
        <format property="today" pattern="yyyy-MM-dd" locale="en,CA"/>
    </tstamp>
    
    <!-- If we only want to run a single diagnostic. -->
    <property name="runOnly" value=""/>
    
    <!-- Are we in debug mode? -->
    <property name="debug" value="no"/>
    
    <!-- For building only a few documents at one go in the HTML. -->
    <property name="docsToBuild" value=""/>
    
    <!-- Folder for HTML website output. -->
    <property name="siteDir" value="${basedir}/products"/>
    
    <!--  Some paths, libs and tasks. (May not all be needed.) -->
    <taskdef resource="net/sf/antcontrib/antcontrib.properties">
        <classpath>
            <pathelement location="${basedir}/lib/ant-contrib.jar"/>
        </classpath>
    </taskdef>
    
    <!-- Location of Saxon jar. -->
    <property name="saxon" value="${basedir}/lib/saxon-he-12.jar"/>
    
    <!-- Location of the TEI Stylesheets. -->
    <property name="teiStylesheets" value="https://raw.githubusercontent.com/TEIC/Stylesheets/refs/heads/released"/>
    
    <!-- The ODD file from which all schemas are built. -->
    <property name="oddFile" value="${basedir}/data/schema/schema.odd"/>
    
    <!-- The RELAXNG schema we generate from the ODD file. -->
    <property name="rngFile" value="${basedir}/data/schema/schema.rng"/>
    
    <!-- The Schematron schema we generate from the ODD file. -->
    <property name="schFile" value="${basedir}/data/schema/schema.sch"/>
    
    <!-- The Schematron from the ODD file compiled into XSLT. -->
    <property name="xslSchematron" value="${basedir}/data/schema/schema.xsl"/>
    
    <!--ODD 2 ODD XSLT (from the TEI GitHub repo)-->
    <property name="odd2odd.xsl" value="${teiStylesheets}/odds/odd2odd.xsl"/>
    
    <!--ODD 2 RNG XSLT (from the TEI framework)-->
    <property name="odd2rng.xsl" value="${teiStylesheets}/profiles/tei/rng/to.xsl"/>
    
    <!--ODD 2 Schematron XSLT (from the TEI framework)-->
    <property name="odd2sch.xsl" value="${teiStylesheets}/odds/extract-isosch.xsl"/>
    
    <!-- SchXslt transpiler (1.7 branch) -->
    <property name="schXslt" value="https://codeberg.org/SchXslt/schxslt2/raw/branch/release-1.7/src/main/resources/content/transpile.xsl"/>
    
    <!-- Jing task for validation of XML. -->
    <taskdef name="jing" classname="com.thaiopensource.relaxng.util.JingTask" 
        classpath="${basedir}/lib/jing.jar"/>
    
    <!-- Source xml fileset. -->
    <fileset id="sourceXml" dir="${basedir}">
        <!-- Data files. -->
        <include name="data/*.xml"/>
        <!-- Templates. -->
        <include name="templates/*.xm_"/>
        <!-- Boilerplate for the site. -->
        <include name="boilerplate/page_template.xml"/>
    </fileset>
    
    <target name="preClean">
        <description>
            TARGET preClean
            Cleans up the products of previous build operations.
        </description>
        <mkdir dir="${basedir}/products"/>
        <delete includeemptydirs="true">
            <fileset dir="${basedir}/products">
                <include name="*"/>
                <include name="**/*"/>
            </fileset>
        </delete>
        <delete file="${basedir}/gitHash.txt"/>
    </target>
    
    <target name="gitHashForSuffix">
        <description>
            TARGET gitHashForSuffix
            This simply outputs the first four characters of the 
            current git commit hash for use by staticSearch as a
            suffix for versioning.
        </description>
        <exec executable="git" dir="${basedir}" outputproperty="gitHash">
            <arg value="rev-parse"/>
            <arg value="HEAD"/>
        </exec>
        <echo file="${basedir}/gitHash.txt" message="${gitHash}"/>
        <replaceregexp file="${basedir}/gitHash.txt" match="^(.{4,4}).+$" replace="\1" flags="s"/>
    </target>
    
    <target name="copyWebResources">
        <description>
            TARGET copyWebResources
            This copies all the ancillary files such as css, js,
            documentation, and images into the output site folder.
        </description>
        <echo message="${echo.separator}"/>
        <echo message="Copying required resources to the 'products' folder."/>
        <copy todir="${basedir}/products/css" preservelastmodified="true">
            <fileset dir="${basedir}/css" includes="*.css"/>
        </copy>
        <copy todir="${basedir}/products/fonts" preservelastmodified="true">
            <fileset dir="${basedir}/fonts"  includes="*.woff2"/>
        </copy>
        <copy todir="${basedir}/products/js" preservelastmodified="true">
            <fileset dir="${basedir}/js"/>
        </copy>
        <!-- <copy todir="${basedir}/products/js" preservelastmodified="true">
            <file file="${basedir}/staticSearch/js/ssHighlight.js"/>
        </copy> -->
        <copy todir="${basedir}/products/images" preservelastmodified="true">
            <fileset dir="${basedir}/images"/>
        </copy>
        <copy todir="${basedir}/products/software" preservelastmodified="true">
            <fileset dir="${basedir}/software"/>
        </copy>
    </target>

    <target name="buildSchema">
        <description>
            TARGET buildSchema
            This makes use of the TEI Stylesheets online to build the ODD file into
            a RNG schema and an XSLT Stylesheet which enacts the Schematron rules 
            from the ODD file.
        </description>
        <!-- First transform the schema. --> 
        <echo message="Initial processing of ODD file..."/>
        <echo message="${echo.separator}"/>
        <java jar="${saxon}" fork="true" failonerror="true">
            <arg line="-s:${oddFile}"/>
            <arg line="-o:${oddFile}.processed"/>
            <arg line="-xsl:'${odd2odd.xsl}'"/>
        </java>
        
        <!-- Now generate the RNG. --> 
        <echo message="Generating RNG..."/>
        <echo message="${echo.separator}"/>
        <java jar="${saxon}" fork="true" failonerror="true">
            <arg line="-s:${oddFile}.processed"/>
            <arg line="-o:${rngFile}"/>
            <arg line="-xsl:'${odd2rng.xsl}'"/>
        </java>
        
        <!-- Next, extract the Schematron. -->
        <echo message="Extracting Schematron..."/>
        <echo message="${echo.separator}"/>
        <java jar="${saxon}" fork="true" failonerror="true">
            <arg line="-s:${oddFile}.processed"/>
            <arg line="-o:${schFile}"/>
            <arg line="-xsl:'${odd2sch.xsl}'"/>
        </java>
        
        <!-- Finally, compile the Schematron. -->
        <echo message="Compiling Schematron XSLT..."/>
        <echo message="${echo.separator}"/>
        <java jar="${saxon}" fork="true" failonerror="true">
            <arg line="-s:${schFile}"/>
            <arg line="-o:${xslSchematron}"/>
            <arg line="-xsl:'${schXslt}'"/>
            <arg line="?schxslt:debug=true()"/>
            <arg line="!indent=yes"/>
        </java>
        
        <!-- And, if not in debug mode, delete the processed ODD. -->
        <if>
            <equals arg1="${debug}" arg2="no"/>
            <then>
                <delete file="${oddFile}.processed"/>
            </then>
        </if>
    </target>
    
    <target name="diagnostics">
        <description>
            TARGET diagnostics
            Runs a range of diagnostic and progress-measuring processes to help with 
            project management.
        </description>
        <echo message="${echo.separator}"/>
        <echo message="Running project diagnostics..."/>
        <java fork="true" classname="net.sf.saxon.Transform" classpath="${saxon}" failonerror="true" dir="${basedir}">
            <arg value="-s:xsl/master_diagnostics.xsl"/>
            <arg value="-xsl:xsl/master_diagnostics.xsl"/> 
            <arg value="baseDir=${basedir}"/>
            <arg value="diagsToRun=${diagsToRun}"/>
            <arg value="--suppressXsltNamespaceCheck:on"/>
        </java>
        <copy todir="products/css">
            <file file="css/diagnostics.css"/>
        </copy>
        <copy todir="products/js">
            <file file="js/diagnostics.js"/>
        </copy>
    </target>
    
    <target name="rngValidateSource">
        <description>
            TARGET rngValidateSource
            This target validates the content of the content
            folder, which contains all the site pages and timeline files.
            These files are validated against the eb11.rng RelaxNG schema.
        </description>
        <echo message="${echo.separator}"/>
        <echo message="Validating the original XML content documents with RelaxNG..."/>
        <jing compactsyntax="false" rngfile="${basedir}/data/schema/schema.rng" failonerror="true">
            <fileset refid="sourceXml"/>
        </jing>
    </target>
    
    <target name="schematronValidateSource">
        <description>
            TARGET schematronValidateSource
            This target validates the content of the data
            folder, which contains all the article files,
            using Schematron. It uses the utilities/eb11Schematron.xsl
            file, which is the set of Schematron rules extracted from the
            schema and compiled into XSLT. Validation results are generated
            and parsed in a single operation, avoiding the necessity to
            output results to a temporary folder and then parse them in a
            separate operation.
        </description>
        <echo message="${echo.separator}"/>
        <echo message="Validating XML source files with project Schematron..."/>
        <java fork="true" classname="net.sf.saxon.Transform" 
            classpath="${saxon}" 
            failonerror="true">
            <jvmarg value="-Xmx2048m"/>
            <arg value="-s:xsl/master_schematron_validation.xsl"/>
            <arg value="-xsl:xsl/master_schematron_validation.xsl"/>
            <arg value="--suppressXsltNamespaceCheck:on"/>
        </java>
        <echo message="${echo.separator}"/>
        <echo message="Schematron validation complete."/>
    </target>
    
    <target name="validateSource">
        <description>
            TARGET validateSource
            This calls the two targets rngValidateSource and 
            schematronValidateSource.
        </description>
        <echo message="${echo.separator}"/>
        <echo message="Validating XML source files..."/>
        <antcall target="rngValidateSource"/>
        <antcall target="schematronValidateSource"/>
    </target>
    
    <target name="buildSite">
        <description>
            TARGET buildSite
            This target builds the entire site.
        </description>
        <echo message="${echo.separator}"/>
        <echo message="Building the website."/>
        <java fork="true" classname="net.sf.saxon.Transform" 
            classpath="${saxon}" 
            failonerror="true">
            <jvmarg value="-Xmx2048m"/>
            <arg value="-s:xsl/master_build_site.xsl"/>
            <arg value="-xsl:xsl/master_build_site.xsl"/>
            <arg value="--suppressXsltNamespaceCheck:on"/>
        </java>
    </target>
    
    <target name="validateSite">
        <description>
            TARGET validateSite
            This target validates the complete collection of XHTML5 documents 
            comprising the output site, using the VNU validator (the same validator used by 
            the W3C's online validation service).
        </description>
        <echo message="${echo.separator}"/>
        <echo message="Validating the HTML pages produced in the build using the VNU validator."/>
        <java jar="${basedir}/lib/vnu.jar" failonerror="false" fork="true">
            <arg line="--filterfile ${basedir}/lib/vnu_filterfile.txt"/>
            <arg value="--format text"/>
            <arg value="--skip-non-html"/>
            <arg value="--errors-only"/>
            <arg value="${basedir}/products"/>
        </java>
    </target>


    <target name="all">
        <description>
            TARGET all
            This target runs the entire build process.
        </description>
        <echo message="${echo.separator}"/>
        <echo message="Running the site build process..."/>
        <antcall target="preClean"/>
        <antcall target="gitHashForSuffix"/>
        <antcall target="validateSource"/>
        <antcall target="copyWebResources"/>
        <!--<antcall target="diagnostics"/>-->
        <antcall target="buildSite"/>
        <antcall target="validateSite"/>
        <echo message="Done!"/>
    </target>
  
</project>